# Generated by Django 6.1.1 on 2026-10-08 08:55

import django.db.models.deletion
import django.utils.timezone
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('info', 'Info'), ('warning', 'Warning')], default='info', max_length=16)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('product_id', models.CharField(max_length=32)),
                ('product_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('savings', 'Savings'), ('investment', 'Investment'), ('thrift', 'Thrift'), ('loan', 'Loan'), ('hire-purchase', 'Hire-Purchase')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('term_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('application', models.JSONField(blank=True, null=True)),
                ('next_of_kin', models.JSONField(blank=True, null=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('receipt', models.FileField(blank=True, upload_to=payments.models.receipt_path)),
                ('receipt_name', models.CharField(blank=True, max_length=255)),
                ('receipt_size', models.PositiveIntegerField(blank=True, null=True)),
                ('receipt_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('paid_to', models.JSONField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('viewed', 'Viewed slip'), ('recommended_approval', 'Recommended approval'), ('recommended_rejection', 'Recommended rejection'), ('approved', 'Final approval'), ('rejected', 'Final rejection')], max_length=32)),
                ('actor_name', models.CharField(max_length=150)),
                ('actor_role', models.CharField(max_length=16)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip_events', to='payments.transaction')),
            ],
            options={
                'ordering': ['at', 'pk'],
            },
        ),
    ]
