# Generated by Django 6.1.1 on 2026-10-08 09:27

import django.db.models.deletion
import django.utils.timezone
import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=16, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=20)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='FacilityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=16, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='payments.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to=payments.models.document_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payments.transaction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('transaction', 'key'), name='one_document_per_key')],
            },
        ),
    ]
