# Generated by Django 6.1.1 on 2026-10-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_withdrawal_withdrawalevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('payment', 'Payment'), ('receipt', 'Receipt'), ('application', 'Application'), ('customer', 'Customer'), ('account', 'Account'), ('withdrawal', 'Withdrawal')], default='account', max_length=16),
        ),
    ]
