# Generated by Django 6.1.1 on 2026-10-07 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=16, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Empire Global', max_length=100)),
                ('support_email', models.EmailField(default='Info@empireglobalbenefits.com', max_length=254)),
                ('support_phone', models.CharField(default='+234 9068410302', max_length=32)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'platform settings',
            },
        ),
    ]
