# Generated by Django 6.1.1 on 2026-10-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='next_of_kin',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
