# Generated by Django 6.1.1 on 2026-10-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_security_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='investment_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='outstanding_loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='savings_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
