"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Dev fallback only; set DJANGO_SECRET_KEY in any shared or production environment
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-syr%)hkwa%6&(=w(8(*dd!q*pa8+1*6qxy@1r&*!+z%fqp1cr0')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]
# Render sets this to the service's own hostname (e.g. empireglobal-backend.onrender.com)
if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
    ALLOWED_HOSTS.append(os.environ['RENDER_EXTERNAL_HOSTNAME'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'core',
    'payments',
    'catalog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves Django admin's CSS/JS in production (there's no separate static file server)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# SQLite locally; Postgres when DATABASE_URL is set (Render provides it)
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600, conn_health_checks=True),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Rate limits are counted in the cache. In production it lives in the database so every
# gunicorn worker shares the same counts (create it with `manage.py createcachetable`).
if os.environ.get('DATABASE_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'django_cache',
        },
    }


AUTH_USER_MODEL = 'accounts.User'


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploaded files (payment receipts, application documents, display pictures). Never served
# directly: receipts and documents are streamed to the owner or an admin by the API.
# With CLOUDINARY_URL set (cloudinary://<api_key>:<api_secret>@<cloud_name>) they're stored in
# Cloudinary as authenticated (private) assets; otherwise on disk under MEDIA_ROOT.
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))
CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL', '')
CLOUDINARY_FOLDER = os.environ.get('CLOUDINARY_FOLDER', 'empire-global')

STORAGES = {
    'default': {
        'BACKEND': 'core.storage.CloudinaryStorage' if CLOUDINARY_URL
        else 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage' if DEBUG
        else 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# EMAIL_PROVIDER=console prints emails to the runserver console (development).
# EMAIL_PROVIDER=resend sends them through the Resend API using RESEND_API_KEY.
EMAIL_PROVIDER = os.environ.get('EMAIL_PROVIDER', 'console').lower()

if EMAIL_PROVIDER == 'resend':
    MAILERS = {
        'default': {
            'BACKEND': 'accounts.mail.ResendEmailBackend',
            'OPTIONS': {'api_key': os.environ.get('RESEND_API_KEY', '')},
        },
    }
else:
    MAILERS = {
        'default': {
            'BACKEND': 'accounts.mail.ConsoleEmailBackend',
        },
    }


DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Empire Global <no-reply@empireglobal.com>')


# Auth / API
# The React app talks to /api through the Vite dev proxy (same origin), so auth
# uses Django's HttpOnly session cookie plus the csrftoken cookie.

# In production the React app is on Vercel, which forwards /api/* to this server (see vercel.json),
# so the browser still sees one origin and the cookies stay first-party.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173').rstrip('/')
CSRF_TRUSTED_ORIGINS = [FRONTEND_URL]
# The forwarded requests may carry the frontend's hostname
if urlparse(FRONTEND_URL).hostname and not DEBUG:
    ALLOWED_HOSTS.append(urlparse(FRONTEND_URL).hostname)

SESSION_COOKIE_AGE = 60 * 60 * 24 * 7
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# Render (and Vercel in front of it) terminate HTTPS and say so in this header
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Render and Vercel already redirect HTTP to HTTPS (and Vercel sends HSTS for the site), so
# Django doesn't redirect itself; that would also break Render's internal health checks.
SILENCED_SYSTEM_CHECKS = ['security.W004', 'security.W008']

OTP_LENGTH = 6
OTP_TTL_SECONDS = 10 * 60
OTP_RESEND_SECONDS = 60
OTP_MAX_ATTEMPTS = 5

# Per-account lockout: this many wrong passwords in a row locks the account for a while
LOGIN_MAX_FAILURES = 5
LOGIN_LOCKOUT_SECONDS = 15 * 60

# When on, admins confirm each sign-in with a code emailed to them. Off by default (email and
# password only); set ADMIN_TWO_FACTOR=true in the environment to turn it back on.
ADMIN_TWO_FACTOR = os.environ.get('ADMIN_TWO_FACTOR', 'false').lower() == 'true'
# How long a password-checked admin has to enter that code
ADMIN_TWO_FACTOR_WINDOW_SECONDS = 10 * 60

# Unverified sign-ups older than this are removed by `manage.py purge_pending_signups`
PENDING_SIGNUP_MAX_AGE_HOURS = 48

PASSWORD_RESET_TIMEOUT = 60 * 60

# Google sign-in for customers. Both come from an OAuth client ("Web application") in Google Cloud
# Console; the button is hidden until both are set. The secret never leaves the server.
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
# How long a first-time Google user has to finish their profile
GOOGLE_SIGNUP_WINDOW_SECONDS = 30 * 60

# First-run setup: POST /api/setup/super-admin/ creates the first Super Admin, and only while
# none exists. Outside DEBUG it also needs this token in an X-Setup-Token header; with no token
# set, the endpoint is off in production.
SETUP_TOKEN = os.environ.get('SETUP_TOKEN', '')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.SessionAuthentication'],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
    'DEFAULT_THROTTLE_CLASSES': ['rest_framework.throttling.ScopedRateThrottle'],
    'DEFAULT_THROTTLE_RATES': {
        'auth_login': '10/min',
        'auth_register': '5/min',
        'auth_otp': '10/min',
        'setup': '5/hour',
        'withdrawals': '10/hour',
        'uploads': '20/hour',
    },
}


# Errors go to stdout so they show up in Render's logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'WARNING'},
}


# Refuse to start in production with settings that would leak data or lose files
if not DEBUG:
    if SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured('Set DJANGO_SECRET_KEY in production.')
    if not CLOUDINARY_URL:
        raise ImproperlyConfigured(
            "Set CLOUDINARY_URL in production: the server's disk is wiped on every deploy, "
            'so receipts, documents and profile pictures must be stored in Cloudinary.'
        )
