# Generated by Django 6.1.1 on 2026-10-08 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('savings', 'Savings'), ('investment', 'Investment'), ('thrift', 'Thrift'), ('loan', 'Loan'), ('hire-purchase', 'Hire-Purchase')], max_length=16)),
                ('description', models.TextField()),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('term_options', models.JSONField(blank=True, null=True)),
                ('expected_return', models.CharField(blank=True, max_length=150)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('clauses', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('item_categories', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
    ]
