# Generated by Django 6.1.1 on 2026-10-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='withdrawal_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
